# Generated by Django 3.0.5 on 2020-05-04 02:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('page_name', models.CharField(max_length=30)),
                ('profile_image', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadtime', models.DateTimeField()),
                ('url', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('views', models.IntegerField()),
                ('creator', models.ManyToManyField(to='videoplatform.Creator')),
            ],
        ),
    ]
