# Generated by Django 3.0.5 on 2020-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplatform', '0002_auto_20200504_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='banner_image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creator',
            name='url_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
